Improve test output
Signed-off-by: Benoit Donneaux <benoit@leastauthority.com>

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -58,5 +58,11 @@ jobs:
       - name: Test binary
         id: test_binary
         run: |
-          ldd ../MoveOffTrac/trac2gitea/trac2gitea | grep 'not found' && { echo FAIL; exit 1; } || echo PASS
-          ./trac2gitea --help 2>&1 | grep '^Usage' && echo PASS || { echo FAIL; exit 1; }
+          echo -n "Test for a static executable:       "
+          ldd ../MoveOffTrac/trac2gitea/trac2gitea | grep -q 'not a dynamic executable' \
+          && echo PASS \
+          || { echo FAIL; exit 1; }
+          echo -n "Test for usage prompt on execution: "
+          ./trac2gitea --help 2>&1 | grep -q '^Usage' \
+          && echo 'PASS' \
+          || { echo 'FAIL'; exit 1; }
